name: cipher_dove
description: "An open-source, offline, zero-ads, basic encryption and decryption tool."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.3.0+1

#
# ======================================================================================================
#

environment:
  sdk: ">=3.4.5 <4.0.0"

#
# ======================================================================================================
#

dependencies:
  flutter:
    sdk: flutter

  # Logging
  logger: ^2.5.0

  # App information provider.
  package_info_plus: ^8.1.0

  # Handles version check.
  version: ^3.0.2

  # Unique id generator.
  uuid: ^4.4.2

  # Handy app's flavor utility.
  # flutter_flavorizr: ^2.2.3

  # Splash screen customization.
  flutter_native_splash: ^2.4.1

  # App icon customization.
  flutter_launcher_icons: ^0.14.1

  # Easy to use package name changer.
  change_app_package_name: ^1.3.0

  # Easy app renaming.
  rename_app: ^1.6.2

  # Native notification.
  flutter_local_notifications: ^19.0.0

  # Cryptographies
  cryptography_plus: ^2.7.0
  cryptography_flutter_plus: ^2.3.2
  crypto: ^3.0.6
  blowfish: ^1.0.2
  sha3: ^0.2.0

  # Time utility.
  intl: ^0.20.2

  # Localization utility.
  # easy_localization: ^3.0.7+1

  # Local database/storage utility.
  shared_preferences: ^2.2.3

  # Handy collection library
  collection: ^1.19.0

  # Powerful state management solution.
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # App routing.
  go_router: ^14.6.1
  go_transitions: ^0.8.0

  # Native share link functionality.
  share_plus: ^10.0.0

  # Native url launcher functionality.
  url_launcher: ^6.3.0

  # Handle network requests.
  dio: ^5.5.0+1
  pretty_dio_logger: ^1.4.0
  internet_connection_checker_plus: ^2.7.1

  # Prevent user to close the app when tapping back button.
  double_back_to_close_app: ^2.1.0

  # App theme font customization.
  google_fonts: ^6.2.1

  # Decorations
  cupertino_icons: ^1.0.8
  icons_plus: ^5.0.0
  toggle_switch: ^2.3.0

#
# ======================================================================================================
#

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Cool & Useful codegen
  build_runner: ^2.4.13

  # Lints
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0

  # Helps code faster and lesser.
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2

  # For testing.
  mocktail: ^1.0.4
  test: ^1.25.8

#
# ======================================================================================================
#

flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/translations/
    - assets/images/splash/
    - assets/images/logos/
    - assets/images/icon/
    - assets/images/bg/
